### ISSUE TITLE
ROS topic is not possible to recieve to rtabmap

### ISSUE THREAD

**Issue by kdhRGT** [sunsided/RoboND-MapMyWorld#1]
Hello sir.

I really love your work. thank you so much to share your project.

I am succeeded to build your project 

but your gazebo world publishes this topic..

/camera/depth/camera_info
/camera/depth/image_raw
/camera/depth/points
/camera/parameter_descriptions
/camera/parameter_updates
/camera/rgb/camera_info
/camera/rgb/image_raw
/camera/rgb/image_raw/compressed
/camera/rgb/image_raw/compressed/parameter_descriptions
/camera/rgb/image_raw/compressed/parameter_updates
/camera/rgb/image_raw/compressedDepth
/camera/rgb/image_raw/compressedDepth/parameter_descriptions
/camera/rgb/image_raw/compressedDepth/parameter_updates
/camera/rgb/image_raw/theora
/camera/rgb/image_raw/theora/parameter_descriptions
/camera/rgb/image_raw/theora/parameter_updates
/clicked_point
/clock
/cmd_vel
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/initialpose
/joint_states
/map
/map_updates
/move_base_simple/goal
/odom
/rosout
/rosout_agg
/scan
/statistics
/tf
/tf_static

But when I did run launch file.

roslaunch map_my_world mapping.launch

rtabmap wanna subscribe 

   /odom \
   /camera/rgb/image_raw/compressed \
   /camera/depth/image_raw/compressedDepth \
   /camera/rgb/camera_info \
   /scan

I don't know where should I change this compress ...

but gazebo doesn't publish about this topics so my project doesn't work.

could you tell me how can I connect with gazebo<->rtabmap for mapping?

here is screen capture from terminal.

![Screenshot from 2022-02-11 14-45-25](https://user-images.githubusercontent.com/99226572/153543298-897cabbd-07bd-4e41-b255-7e3bc03225d7.png)

Thank you so much

I will wait your answer 

I wanna know that how can I change the subscribe topic name just 'raw' data

Or 

change the publish gazebo setup

best regards

**Comment by sunsided** [comment]
Hi! You need to have multiple things running simultaneously:

1. `roscore` (it should be started automatically through `roslaunch` however)
2. The world itself (`roslaunch map_my_world world.launch`) and
3. Either mapping _or_ localization, i.e.
    - `roslaunch map_my_world mapping.launch` or
    - `roslaunch map_my_world localization.launch`
4. Optionally, teleoperation for mapping (`rosrun teleop_twist_keyboard teleop_twist_keyboard.py`)

Note that when you run Gazebo for the first time (e.g. through `roslaunch map_my_world world.launch`), it might take a long time to start.

If you only have one terminal, you can use `&` to send a command to the background.

```
roslaunch map_my_world world.launch &
roslaunch map_my_world mapping.launch &
rosrun teleop_twist_keyboard teleop_twist_keyboard.py
```

If you use the Docker image I provided, note that you can create multiple terminals through [`docker run`](https://docs.docker.com/engine/reference/commandline/run/) (e.g. via `run_nvidia.sh`) starting the container) and [`docker exec <containername> bash`](https://docs.docker.com/engine/reference/commandline/exec/) (connecting to an already running container).

**Comment by kdhRGT** [comment]
Thank you so much, it was very helpful~!
